### ISSUE TITLE
Pulling from github causes BiocCheck error

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/bugsigdbr#19]
@jwokaty @lwaldron just a heads up that our rework of bugsigdbr pulling from github/BugSigDBExports (https://github.com/waldronlab/BugSigDB/issues/94#issuecomment-903121949) is causing us a [BiocCheck error](https://github.com/waldronlab/bugsigdbr/runs/3525578534?check_suite_focus=true):

```
ERROR: Avoid references to external hosting platforms
      Found in files:
        bugsigdb.R (line 13, column 22)
```

I had experienced this before when I tried pulling from dropbox for another package, but here it seems to imply that Bioc doesn't like us to pull files from github. I am not sure how to best address this and whether this would also apply to pulling files from zenodo. We might need some input from the core team. Maybe @LiNk-NY has the corresponding best practices for us?

**Comment by lgeistlinger** [comment]
Not a clean solution (rather a hack), but masking the github url with a tinyurl works if we just wanted the error to go away. Would still be good to understand what's the recommended Bioc solution for such situations.

**Comment by LiNk-NY** [comment]
Hi Ludwig, @lgeistlinger 

Yes, there is some discussion here https://github.com/Bioconductor/BiocCheck/issues/75 as to the reasons.

The best bet is to either put the data in the package (if it is small enough) or on Experiment/Annotation-Hub.

**Comment by lgeistlinger** [comment]
Thank you @LiNk-NY for pointing us to the corresponding BiocCheck issue. @jwokaty I just discussed with @lwaldron and following his remarks on the BiocCheck issue and the suitability of the current solution for our purposes we decided to go ahead as-is.
