### ISSUE TITLE
Add importBugSigDB to R package

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/bugsigdbr#2]
See https://github.com/waldronlab/bugSetEnrichment/blob/d6ab1fdca906f8af0f7dd1f7920360c69b387a1c/R/bugsigdb_analyses.R#L13

@LiNk-NY would you take a look at the caching functionality and advise if we should copy it here?

**Comment by lwaldron** [comment]
I agree with you @lgeistlinger , moving all these issues over to `waldronlab/bugsigdbr`.

**Comment by lgeistlinger** [comment]
done via 61c669b - you are all good to go
