### ISSUE TITLE
Update Github actions

### ISSUE THREAD

**Issue by jwokaty** [waldronlab/bugsigdbr#24]
Update Github actions to use 3.15.

**Comment by lgeistlinger** [comment]
fixed via [bb91ddb](https://github.com/waldronlab/bugsigdbr/commit/bb91ddbe8ee908c70164bbe646ea17ef42890d0c) by @lwaldron

**Comment by lwaldron** [comment]
Will still have to be done for macOS and Windows though. There's something funny in this Action in that you can only choose one particular R and bioc version.

**Comment by lgeistlinger** [comment]
Hi @jwokaty there seems to a recent problem with the GHA giving back a

```
Unable to resolve action `r-lib/actions@master`, unable to find version `master`
```

Can you be so good and take a look at that? Thanks!
