### ISSUE TITLE
importBugSigDB(version="devel") is missing studies

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/bugsigdbr#27]
Reproducible example:
```
library(bugsigdbr)
library(dplyr)
bsdb <- bugsigdbr::importBugSigDB(version="devel")
bsdb %>% filter(Curator=='Fcuevas3') %>% group_by(PMID) %>% summarize(study=first(Study))
```

This returns 4 studies:
```
      PMID study    
     <dbl> <chr>    
1 28449715 Study 560
2 29501802 Study 600
3 30576008 Study 537
4 31354427 Study 554
```

This Curator, Fcuevas3, has curated at least 10 studies. Some of the studies that are missing include:
https://bugsigdb.org/Study_568 (curated 11/29/21)
https://bugsigdb.org/Study_601 (curated 1/18/22)

My understanding is that if this is pulling from the Github repo it should be current to within the last few days.

I have confirmed that this is not an issue with the filter or the `bsdb` object not playing nice with dplyr as `bsdb[bsdb$Study=="Study 568",]` returns 0 rows.

**Comment by lgeistlinger** [comment]
Hi @cmirzayi : note that the export only includes content that is rendered "complete". the two examples that you are listing consists of content that is rendered "incomplete" and is accordingly excluded from the export.

**Comment by lwaldron** [comment]
It's correct behavior then, we need to have reviews check https://bugsigdb.org/Special:Ask/-5B-5BState::Incomplete-5D-5D/mainlabel%3D/offset%3D0/format%3Dol/searchlabel%3DIncomplete-20pages (linked to from the help page) for pages marked as Incomplete that are actually Complete, and make sure curators know to change the status to complete when they finish a study. @ftzohra22 @rimsha1
