### ISSUE TITLE
all(grepl("^[A-Z][a-z ]+$", names(s))) is not TRUE

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/bugsigdbr#29]
This new test failure is occurring in bioc-devel 3.15 (but not in 3.14), see:

* http://bioconductor.org/checkResults/devel/bioc-LATEST/bugsigdbr/

or:

* https://github.com/waldronlab/bugsigdbr/runs/5628202350?check_suite_focus=true#step:22:96

**Comment by lgeistlinger** [comment]
fixed via [bb91ddb](https://github.com/waldronlab/bugsigdbr/commit/bb91ddbe8ee908c70164bbe646ea17ef42890d0c)
