### ISSUE TITLE
BugSigDB 1.1.0 release (for Bioconductor 3.15)

### ISSUE THREAD

**Issue by jwokaty** [waldronlab/bugsigdbr#30]
Opening an issue so that we can do a release with Bioconductor.

**Comment by lgeistlinger** [comment]
Thanks @jwokaty. This will be the BugSigDB 1.1.0 release, which will be the stable release for mid-April to mid-October. Maybe also open an issue at BugSigDBExports?

In agreement with the [Bioc release schedule](https://bioconductor.org/developers/release-schedule/), the plan would be:

1. @lgeistlinger checks/reviews April 10 export and applies necessary modifications (if any)
2. @jwokaty: 1) releases the April 17 export as the BugSigDB 1.1.0 release on zenodo, and 2) adapts `bugsigdbr::importBugSigDB` to pull the new stable release.
3. April 25: last day to commit changes to the Bioc 3.15 branch

**Comment by jwokaty** [comment]
@lgeistlinger I just want to confirm that we're okay to do the export today?

**Comment by lgeistlinger** [comment]
Thanks @jwokaty - yes, I screened through the files and things are looking good. Ready to go for release 1.1.0.
