### ISSUE TITLE
3.16 Release?

### ISSUE THREAD

**Issue by jwokaty** [waldronlab/bugsigdbr#34]
@lgeistlinger I know it's very late, but do we need to do a process similar to https://github.com/waldronlab/bugsigdbr/issues/30 with a release on zenodo? (I apologize, it's been very busy.)

**Comment by lgeistlinger** [comment]
Thanks for raising this @jwokaty. There are two issues that I would like to sort out prior to the new 1.2.0 release (https://github.com/waldronlab/BugSigDB/issues/111 and https://github.com/waldronlab/BugSigDB/issues/151), so I guess we will need to sneak that in at some point over the course of November as I don't expect that to be sorted out in time for the Bioc 3.16 release.
