### ISSUE TITLE
Create a unit test for the size of the bugsigdb export

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/bugsigdbr#58]
Given the issues we've experienced with inconsistent exports from BugSigDB (now hopefully alleviated due to better resource allocation), we should have a unit test that checks if the imported data is smaller than expected.

I will develop this test and report back when it's ready.

**Comment by cmirzayi** [comment]
There was an existing unit test which I modified. Pull request is open as https://github.com/waldronlab/bugsigdbr/pull/59

**Comment by lgeistlinger** [comment]
incorporated in [5b35f87](https://github.com/waldronlab/bugsigdbr/commit/5b35f874f1ebc58594b7d2a8926bfc5ba1d76c9c)
