### ISSUE TITLE
Bioc submission

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/bugsigdbr#6]
Hi @jwokaty @lwaldron:

I just finalized what I think is a first working version of the BugSigDB R/Bioc companion package.
I think you likely want to have a closer look into the functionality documented in the vignette of the `bugsigdbr` package here.

If you also think we are good to go @lwaldron, my question would be: @jwokaty would you be interested in taking on the actual submission to Bioconductor by opening a new issue in the Bioconductor [Contributions repository](https://github.com/Bioconductor/Contributions/issues/new). I am happy to help where needed, but maybe you would like to get more familiar with the actual submission + package review process?

**Comment by jwokaty** [comment]
@lgeistlinger Yes! I very much appreciate that.

**Comment by lgeistlinger** [comment]
Hi @lwaldron : just checking in whether we have your thumbs-up to go ahead with the submission to Bioconductor?

**Comment by lwaldron** [comment]
Thumbs up from me. Go for it, @jwokaty .

**Comment by lgeistlinger** [comment]
Hi @jwokaty - thought I quickly check in with you whether you have questions regarding the submission. For the beginning it's not more than opening an issue here: https://github.com/Bioconductor/Contributions/issues - but we can also have a quick chat if you'd like to clarify some details. We'd just like to be able to say "submitted to Bioconductor" for introduction at the upcoming Bioc conference (Aug 5-6). Thanks!

**Comment by jwokaty** [comment]
@lgeistlinger I will follow up with you tomorrow if I have any questions and I'll submit it after that.

**Comment by lgeistlinger** [comment]
Sounds good.

**Comment by jwokaty** [comment]
I submitted. Should I close this issue?

**Comment by lgeistlinger** [comment]
Cool, thanks! Yes, let's close here and let's continue monitoring over there.

**Comment by lwaldron** [comment]
Just to have a cross-reference: https://github.com/Bioconductor/Contributions/issues/2200
